### ISSUE TITLE
💣 ISSUE - <buildlogic을 적용합니다>

### ISSUE THREAD

**Issue by answad** [Team-Wander/Wandering-Android#11]
### Summary

feature, core 구조의 멀티모듈을 사용하고싶습니다

### Reproduction Steps

```bash
nowinandroid 나 다른 레포지토리를 보다보면 buildlogic을 많이 사용해서
```

**Comment by audgns10** [comment]
그런데 now in android의 구조를 따른게 아닌 multi module 구조로 app, data, domain, presentation 모듈만이 존재하는 것으로 보이는데 여러 모듈을 사용하게 되었을때 중복 코드를 줄이기 위한 목적인 build-logic을 사용하는 것이 좋은 방안이 맞는지 생각이 듭니다. build-logic을 사용하신다면 일단 세팅은 하겠습니다. buildSrc로 유지를 하실건가요? 아니면 build-logic을 사용하실건가요?
@answad

**Comment by answad** [comment]
build-logic을 사용하는 이유와 현제 상황이 맞지 않는것 같아서 buildSrc로 유지하기로 했습니다
